[package]
name = "ewok"
version = "0.1.0"
authors = ["Michael Sproul <micsproul@gmail.com>"]

[dependencies]
rand = "0.3"
itertools = "0.6"
maplit = "0.1"
log = "0.3"
env_logger = "0.4"

[[bin]]
name = "ewok"
doc = false

[profile.release]
debug = true
